spring:
  application:
    name: sbd
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orclpdb
    username: sbd
    password: sbd
    driver-class-name: oracle.jdbc.driver.OracleDriver
  flyway:
    baseline-on-migrate: true
    schemas: SBD
    default-schema: SBD
